local builtin = require("telescope.builtin")
vim.keymap.set('n','<leader>ff',builtin.find_files,{})
vim.keymap.set('n','<leader>fg',builtin.live_grep,{})
vim.keymap.set('n','<leader>fb',builtin.buffers,{})
vim.keymap.set('n','<leader>h',builtin.help_tags,{})
vim.keymap.set('n','<leader>fs',builtin.treesitter,{})
vim.keymap.set('n','<leader>fc',builtin.current_buffer_fuzzy_find,{})
vim.keymap.set('n','<leader>fd',builtin.diagnostics,{})
vim.keymap.set('n','<leader>r',builtin.resume,{})
